### ISSUE TITLE
Support for VrayCurvature Texture

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#101]
VrayCurvature is already in the plugin list. Is usefull for creating nice aged edges (eg.: metals)
Would be nice to have it in Vray for Blender.

VrayDirt is a workaround but it gives some issues thin thin surfaces, as described here:
http://forums.chaosgroup.com/showthread.php?76905-VrayDirt-from-angle-instead-of-distance-aka-Cavity-Shader

**Comment by bdancer** [comment]
Done: https://github.com/bdancer/plugins_desc/commit/e6faeacbe2e0dbf496f0669e807ddc7fd2df8987
Exporter update should help.
