### ISSUE TITLE
Maps values

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#102]
Hi! I dont know how to set maps values (like 10 for reflect) in blender node setup. And what number -5 3dmax bump is in blender bump?
![untitled-12](https://cloud.githubusercontent.com/assets/11031197/8129359/d12b5d0a-1108-11e5-916f-4e550e996880.jpg)
 I have material with reflect color and reflect glossines 0,95 but when I connect image texture that values dissapear.
![untitled-2](https://cloud.githubusercontent.com/assets/11031197/8129465/ae255cce-1109-11e5-810d-0a68cae8a972.jpg)

**Comment by bdancer** [comment]
1. You could use "Image Texture" node, it's simplier to use then "Bitmap Buffer"+"Bitmap Texture"
2. Use "Color Operations" / "Float Operations" node to multiply values.
3. Bump has it's own multiplier.

**Comment by pietruh00s** [comment]
1) I know :)
2) In bitmap texture node white Color multiplier means the same as 100 in maps in 3dsmax? 
3) Default bump in 3dsmax is 30 and in blender is 0,1. So what i have to set to achieve 3dsmax -5 value?

**Comment by bdancer** [comment]
1. Great =)

2. Mult value meaning depends on map type. Afair for everything except bump / displace this multiplier is a like a percentage (0-100%). For bump / displace, it means the amount of effect + direction.
"Color Mult" is smth like 0-100% multiplier.

3. -0.02

I was suggesting using smth like this:
![2015_06_12_001](https://cloud.githubusercontent.com/assets/319784/8130314/faf6c53c-1119-11e5-9612-0f5729da282d.png)

**Comment by pietruh00s** [comment]
So if map reflect is 10 I need to set 0,1 in Mult A in color operations? What if I have RGlossines 0,95 and I connect image file texture and I lost ability to change and set this value? I need to set Mult A to 0,95?

**Comment by bdancer** [comment]
> So if map reflect is 10 I need to set 0,1 in Mult A in color operations?

Yes.

> What if I have RGlossines 0,95 and I connect image file texture and I lost ability to change and set this value?

RGlossines 0,95 is not a multiplier it is a value. When you connect a texture it's values are replacing this value completely.

> I need to set Mult A to 0,95?

When you will set this mult white color in texture (1.0) will become 0.95 (all other correspondingly). So, depending on your needs.

PS: Actually, I think it won't be a big issue to add such multipliers directly on nodes.

**Comment by bdancer** [comment]
But anyway, I don't wanna match vb shading setup with 3ds max (basically because there is also V-Ray for Maya and so will need to match it also then which is practically impossible to match 2 packages at once =)

**Comment by pietruh00s** [comment]
I understand you, but I'm trying to move some materials from 3dsmax to blender. Previously I worked with Cycles and now I'm learning Vray and a lot of material tutorials are made in 3dsmax. This thread isnt issue thread it is more like how to achieve similar effects (I can't find any site for discussion about vray in blender)  :)

**Comment by bdancer** [comment]
You could ask questions on our forum: http://forums.chaosgroup.com/forumdisplay.php?177-V-Ray-for-Blender

**Comment by bdancer** [comment]
Every linked socket now has a multiplier:
![vb30_linked_socket_mult](https://cloud.githubusercontent.com/assets/319784/8502705/ddf93a42-21bc-11e5-8986-942915e264bd.png)
