### ISSUE TITLE
New node editor

### ISSUE THREAD

**Issue by Andrewson3D** [bdancer/blender-for-vray#103]
Hi guys!
I need help connecting the bump map and normal map nodes in the new node editor of the Vray\Blender and how to adjust them.

And I need to know how to use the dome node (light), I should to connect it which node?

**Comment by bdancer** [comment]
Hi, check those images, hope it helps:

* [Bump / Normal Mapping](https://raw.githubusercontent.com/bdancer/vb-wiki/master/images/nodes/vb30_bump_mapping.png)

* [IBL (Dome Light | Image-Based Lighting)](https://raw.githubusercontent.com/bdancer/vb-wiki/master/images/nodes/vb30_nodes_ibl.png)

**Comment by Andrewson3D** [comment]
Thank you very much for your help! I was really needing it
