### ISSUE TITLE
Is it possible to preview displacement?

### ISSUE THREAD

**Issue by Zaurio** [bdancer/blender-for-vray#108]
Is it possible to preview displacement? As i remember on previous non-nodal versions were such feature.

**Comment by bdancer** [comment]
That's not possible.

**Comment by bdancer** [comment]
Apparently it was possible =) Fixes with https://github.com/bdancer/blender-for-vray/commit/e262621b68864dc74e3ff4347501a79ffeb23534 and https://github.com/bdancer/vb30/commit/e646b09123a1a03b10edf98ae4eaeea520bb1f1d
