### ISSUE TITLE
vb30: Fresnel reflection

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#112]
Hello,

I've problem with all my scenes. My build is Hash: 9732479 from 2015-07-31. All materials have now automatic Fresnel option picked. Maybe anybody has the same problem? Bdancer can you fix this?

**Comment by Anonim001** [comment]
I confirm it but I am not sure if it is an issue.

**Comment by kontrolermpl** [comment]
OK, Bdancer give me answer, that this is standard wit new build. I changed in "brdfvraymtl.json" True to False for Fresnel reflections and it work fine now. In my opinion it is quite good to pick fresnel option as default. In all my scenes that I made before this change, all materials for example metals (there's no fresnel reflection) get this option on, and render give me bad results.
