### ISSUE TITLE
Linking VRay proxies

### ISSUE THREAD

**Issue by Anonim001** [bdancer/blender-for-vray#113]
VRay proxies don't work if they are linked from another blend file, because 'object tree' isn't connected with the proxy preview mesh by default. I have to choose object tree for each linked proxy by hand.

**Comment by Anonim001** [comment]
And even if I choose the object tree by hand, after reopening the file these connection disappear.

**Comment by bdancer** [comment]
Works fine for me. Are you sure proxy tree is still attached in the linked blendfile? May be you saved it in non-patched Blender and the connection was lost...

**Comment by Anonim001** [comment]
I'd forgotten to mention that I made proxy of linked object (ctrl + alt + p) in order to move the VRayProxy object. Then I saved and reopened blend file and VRayProxy wasn't working, until I selected object tree by hand.

**Comment by bdancer** [comment]
I guess it's not working because you have a relative path to a *.vrmesh file and when you've made your object local this path is not treated relative to the current blend-file not the linked one.

I'm not sure this will be possible to workaround, try using absolute path in VRayProxy node.

**Comment by Anonim001** [comment]
hmm, I've noticed it and I am using absolute path. The issue imho is there:
new file-> link VRayProxy preview object -> make proxy (ctrl + alt + p) -> save file:
VRay proxy object tree looks like this:
![before](https://cloud.githubusercontent.com/assets/13710958/9437236/6e25705c-4a55-11e5-8ac1-839246e4242f.jpg)

after reopening blend file the connection disappear
![after](https://cloud.githubusercontent.com/assets/13710958/9437238/718ee890-4a55-11e5-8bbc-be83cfd91c7c.jpg)

but the node tree exists:
![list](https://cloud.githubusercontent.com/assets/13710958/9437615/e2f62f6e-4a57-11e5-98fb-fc1613dfd434.jpg)

------------------------------------------------

To workaround this problem I make the object tree local:
linked:
![proxylinked](https://cloud.githubusercontent.com/assets/13710958/9437417/8491371c-4a56-11e5-9986-a5c2d375048d.jpg)
local:
![proxylocal](https://cloud.githubusercontent.com/assets/13710958/9437421/8d32971c-4a56-11e5-9104-699805d04c79.jpg)


and after reopening the file the object tree remains connected to the vrayproxy object
![before](https://cloud.githubusercontent.com/assets/13710958/9437461/c1bf0696-4a56-11e5-9c3e-e29afa2358c3.jpg)

(btw. I am using the latest version from nightlies.chaosgroup.com)

**Comment by bdancer** [comment]
Seems like this workaround is the only way...

**Comment by Anonim001** [comment]
:(
