### ISSUE TITLE
Random color/value doesn't work when using Particle System

### ISSUE THREAD

**Issue by Anonim001** [bdancer/blender-for-vray#114]
Objects placed by hand:
![1](https://cloud.githubusercontent.com/assets/13710958/9444829/1bb1f528-4a89-11e5-84d8-7e8c107c867d.jpg)

Particle System (Type: Hair)
![2](https://cloud.githubusercontent.com/assets/13710958/9444841/3373423e-4a89-11e5-8e85-f9af79e464d5.jpg)

Material:
![material](https://cloud.githubusercontent.com/assets/13710958/9444796/ed5caf9c-4a88-11e5-8c72-a5ce77215943.jpg)

(Also material from wiki using Sampler node doesn't work with Particle System)
BTW: Blender Cycles supports randomization when using Particle System.
This feature / fixing issue would be very helpful in creating realistic forest by changing HUE of every tree.

**Comment by bdancer** [comment]
Disable "Use Instancer for dupli/particles" in Advanced object panel.

**Comment by Anonim001** [comment]
Thanks.
(How did u learn programming in Blender and VRay from the technical side? Do you recommend some books, websites? Let's say I'd like to split the Standard Material and SSS2 on many small, simply nodes (like in Cycles). How hard could it be? )

**Comment by bdancer** [comment]
> How did u learn programming in Blender and VRay from the technical side?

Oh, that's a long story =)

> Let's say I'd like to split the Standard Material and SSS2 on many small, simply nodes 

SSS2 is a single V-Ray plugin - you can't split it (but you could mix it with Layered BRDF with other BRDFs).

"Standard Material" is VRayMtl (BRDF) + Bump (BRDF) + Single (Material) + Material ID (Material)

VRayMtl is also a single V-Ray plugin, but could be composed from Layered (BRDF) that mixes: Diffuse (BRDF) + Mirror / Blinn / Phong / etc (reflection layer) + Glass / Glass Glossy / etc (refraction layer).
