### ISSUE TITLE
Group input doesn't work

### ISSUE THREAD

**Issue by Anonim001** [bdancer/blender-for-vray#116]
Material:
![materialgroup](https://cloud.githubusercontent.com/assets/13710958/9446052/c4592c86-4a8f-11e5-89ba-3ea920734323.jpg)
Group:
![group](https://cloud.githubusercontent.com/assets/13710958/9446053/c6ab554a-4a8f-11e5-9d46-ca7646d900c5.jpg)
Result:
![result](https://cloud.githubusercontent.com/assets/13710958/9446054/c7238218-4a8f-11e5-8251-40408c69fbe9.jpg)

There is a problem with reading input group data.

**Comment by bdancer** [comment]
Thant's strange, thanks for the report, I'll fix asap.

**Comment by bdancer** [comment]
I've made a fix: https://github.com/bdancer/blender-for-vray/commit/161701d360513c114f2bf08ef60133f55b58f4bc New Build is ready, could you pls check if it works for you?

**Comment by Anonim001** [comment]
Works perfectly. Thanks
