### ISSUE TITLE
GGX Brdf type - control GTR tail falloff

### ISSUE THREAD

**Issue by jkntdo** [bdancer/blender-for-vray#118]
As title says, is there a way to control the GTR tail falloff of the ggx brdf type? It looks like it's set to a constant value.

**Comment by bdancer** [comment]
I've added a new option "GTR Falloff": https://github.com/bdancer/plugins_desc/commit/746b231e413e264a58318c86a79893ce2d29acbe

Please, try if it'll work for you. "Update Exporter" will help (https://github.com/bdancer/vb30/wiki).

**Comment by jkntdo** [comment]
Works perfectly, thanks for your amazing work!
