### ISSUE TITLE
Rendering using GPU & RT

### ISSUE THREAD

**Issue by Anonim001** [bdancer/blender-for-vray#119]
And again me,
Realtime seems not working either on CPU and GPU. By not working I mean it doesn't refresh the scene even if I move, scale, rotate an object or change material's properties.
Is it available to add an ability to change a rendering device from CPU to GPU and vice versa for a final image (not RT)?

--------------
(I am buying new rendering machine. Should I invest more in CPU or GPU?)

**Comment by bdancer** [comment]
> By not working I mean it doesn't refresh the scene even if I move, scale, rotate an object or change material's properties

Realtime update is not supported by V-Ray Standalone.

> Is it available to add an ability to change a rendering device from CPU to GPU and vice versa for a final image (not RT)?

Yes, enable "Realtime Engine" and you'll see the control "Device" on "Realtime Engine" panel.

**Comment by Anonim001** [comment]
What version of VRay supports RT and will work with Blender?

**Comment by bdancer** [comment]
> and will work with Blender?

We're working on this right now (https://www.youtube.com/watch?v=yB_rHZSAG-E).

**Comment by Anonim001** [comment]
I am a little bit confused. In the video are you using VRay Standalone or a special unrealesed version? If I have VRay Standalone and I want realtime update I have to wait for new Blender for VRay or buy unavailable yet VRay Workstation for Blender?

**Comment by bdancer** [comment]
On a video I'm using a network server based on V-Ray Application SDK. I can't say anything more right now.

**Comment by Anonim001** [comment]
Thanks
