### ISSUE TITLE
Nodes: Reroute issue

### ISSUE THREAD

**Issue by Anonim001** [bdancer/blender-for-vray#120]
Nodes:
![nodes](https://cloud.githubusercontent.com/assets/13710958/9832292/7536f9d0-5976-11e5-8e10-0ce949679c69.jpg)
Result:
![result](https://cloud.githubusercontent.com/assets/13710958/9832293/75e83fba-5976-11e5-82c8-4498996fd59d.jpg)

(It worked, probably in this build: 20150821)

**Comment by bdancer** [comment]
Fixed with: https://github.com/bdancer/blender-for-vray/commit/148e7d7ab8a0920b58ff57fe7ee4d5428943ff87
I'll rebuild tomorrow.

**Comment by bdancer** [comment]
Windows build uploaded, please, check if it fixes the issue for you.

**Comment by Anonim001** [comment]
Thanks
