### ISSUE TITLE
How to import materials from .vrscene

### ISSUE THREAD

**Issue by satz0249** [bdancer/blender-for-vray#123]
I tried to import material from .vrscene by File --> Import --> vray:import materials 

and in the import panel there are 4 base types. Which ever i chose and hit import material, nothing seems to happen after that. 

What are these base types and how to import the vraymtl.

I dont want to use the VRmat since it doesnt allow to make changes to the material.

Thanks

**Comment by bdancer** [comment]
Check Blender's console log for errors. If there are any share the vrscene file pls.

**Comment by satz0249** [comment]
No changes in the console.The command line is same as it was before selecting the import option, not even an error msg .

**Comment by bdancer** [comment]
Could you share this vrscene?

**Comment by satz0249** [comment]
Sure. 
https://drive.google.com/file/d/0B_IJ_C6us9_oUWlDTWdidEJ6SlE/view

This is the file. I downloaded from a website for vray materials in .vrscene format 

I am facing this problem not only with this particular vrscene, but any vrscene that i try to import doesnt have any response.

**Comment by bdancer** [comment]
Tnx, I've found the issue why scene was not parsed - https://github.com/bdancer/vray_tools/commit/4e8a3e86c77ed9285ff25885b603684c64967caa.
Anyway this feature was not tested much, will be nice to see how it'll work for you.

**Comment by satz0249** [comment]
Thankyou Andrei, waiting for the release of the next build :+1:

**Comment by bdancer** [comment]
This fix is already uploaded to the https://nightlies.chaosgroup.com/main#/blender.

**Comment by satz0249** [comment]
Works Fantastic . Thanks a ton :)
