### ISSUE TITLE
vb30: Caustic with Vray sky

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#124]
Hi,

When I use Vray sky texture for lightning my scene and pick caustic calculation, whole render is overexposed. This work correct when I use for example Area light only.

Please check it bdancer.

**Comment by Anonim001** [comment]
Cannot recreate the issue. Could you upload the file?

**Comment by kontrolermpl** [comment]
Please look at this:

http://sendfile.es/pokaz/552513---cbeh.html

**Comment by Anonim001** [comment]
Change multiplier value to 0.0001 (and subdivisions to 8 for a material to speed up rendering). This parameter should be remaped to values between 1-100.
![github](https://cloud.githubusercontent.com/assets/13710958/10946490/cfb94950-8322-11e5-9e1d-8506bb55fe6f.png)

**Comment by kontrolermpl** [comment]
Thank you very much for answer!
