### ISSUE TITLE
GGX brdf type - V-Ray2.5/ V2B 2.76.1

### ISSUE THREAD

**Issue by voytov** [bdancer/blender-for-vray#125]
Hello, when I changed from build 2.74 to 2.76.1 I noticed materials with brdf type GGX set are not being rendered anymore...
Any solutions?
Thanks!

**Comment by bdancer** [comment]
Are you V-Ray 3.x?

**Comment by voytov** [comment]
No. The thing is I was able to use this shader with:
vrayblender3-2.74-60092-dfbb876-fd9aca6-x86_64-windows  plus
vray_adv_24501_maya2012_x64_25506 engine

...then ported my things to other machine, and it doesn't work nor with latest nightly of 2.76 and engine vray_adv_24501_maya2012_x64_25506, nor with that old 2.74 nightly..

Maybe that's not a bug but a feature... I don't know now... So I'm asking actually: should it work?

**Comment by bdancer** [comment]
It should work in V-Ray 3.x only that's why I'm asking...

**Comment by voytov** [comment]
Thanks, I suspected so...
