### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#131]
Small issue but I keep seeing it and bothers me :) In the 3D View and Node Editor are no icons for Increment and Offset.
![untitled-1](https://cloud.githubusercontent.com/assets/11031197/11585943/f1c79736-9a6f-11e5-800a-e27d29e265ac.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/11031197/11585948/f600b62a-9a6f-11e5-9d68-b9589e6759e3.jpg)

**Comment by bdancer** [comment]
Thanks! Fixed with https://github.com/bdancer/vb25-patch/commit/956169d87b574c9a78251ac22e05b2178e741e67
