### ISSUE TITLE
vb30: Render region

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#133]
Hello,

I have the last version of Vray blender and I noticed, that render region option with picked Crop doesn't work. Can you check it Bdancer?

**Comment by bdancer** [comment]
Works fine for me, try updating V-Ray (there was such an issue in some nightly build a few months ago).

**Comment by v45c0** [comment]
Doesn't work for me too. I have vray for maya 3.10.01. Where can I get newer builds?

**Comment by kontrolermpl** [comment]
I downloaded last version again, and it seems to still not work

**Comment by bdancer** [comment]
> I downloaded last version again

Last version of V-Ray?

**Comment by kontrolermpl** [comment]
I meant last version of blender with vray additions :)

**Comment by bdancer** [comment]
Afair, the issue with crop was in V-Ray Standalone itself, so try some V-Ray's nightly build.

**Comment by kontrolermpl** [comment]
I installed yesterday's Vray Standalone 3.3 and now it's O.K.
