### ISSUE TITLE
Problems with exporting objects with drivers and parenting.

### ISSUE THREAD

**Issue by Zaurio** [bdancer/blender-for-vray#135]
objects with driver animations is not exported properly when rendering animation with Full range option, but it's ok in frame by frame mode. https://www.sendspace.com/file/u436t2 here is a project. objects have not to move, or grow.

**Comment by bdancer** [comment]
Why the issue is closed? Is it working or not?

**Comment by Zaurio** [comment]
Hello, Andrey! Sorry for troubling)  I'm not quire sure that problem was in exporter. The problem was because "camera path" was checked on GI settings and i think that's why parented to the camera objects moved.
