### ISSUE TITLE
vb30 or vb35

### ISSUE THREAD

**Issue by mirlip** [bdancer/blender-for-vray#139]
Hi all,
What are the differences between the vb30 and vb 35 version? Is it possible to get the contrib plugins in your git repo or are they already there?
Regards,
Mirlip

**Comment by bdancer** [comment]
> What are the differences between the vb30 and vb 35 version?

vb35 is an upcoming version. It will not work for you and is not yes supported.

> Is it possible to get the contrib plugins

What does this mean?

**Comment by mirlip** [comment]
there are 2 plugin folders in Blender, official ones in addons and community ones in addons_contrib. Thank you for your quick answers :)
