### ISSUE TITLE
materials from 3DSmax

### ISSUE THREAD

**Issue by mirlip** [bdancer/blender-for-vray#140]
Hi,
What is the best way to get Vray materials from 3DSmax to Blender? Is there a script? Should we export as vray-proxy that can be used in Blender for V-ray? other solutions?
Best regards,
Mirlip

**Comment by bdancer** [comment]
1. Export into vrscene file then import or use in VRmat node.
2. Export into vismat and use in VRmat node.

**Comment by mirlip** [comment]
Is everything material-wise supported by the vrscene/vismat import plugin?

**Comment by bdancer** [comment]
@mirlip if referenced with VRmat node then yes, if you actually want to import the contents - then try-test-report-errors.

**Comment by mirlip** [comment]
ok. If corrections/additions have to be made, will the 3.5 branch be available to the current 3.x standalone customers?

**Comment by bdancer** [comment]
Sorry, I don't get - 3.5 version of what?

**Comment by mirlip** [comment]
I just wanted to be sure, that if something is not working well in the vb30 branch, that the fix will be made available to current customers. I'll buy a license of V-Ray standalone soon and wanted to know if I can buy tomorrow or better wait for the vb35 branch to come out.

**Comment by bdancer** [comment]
I'll remove this branch to not to confuse you.
