### ISSUE TITLE
Mute nodes

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#141]
Is any way to mute nodes like in Cycles? M key doesn't work :(

**Comment by bdancer** [comment]
I've added support for node muting with https://github.com/bdancer/vb30/commit/c8483e1bebe45084c0f574550c458e9b5f77d413 and https://github.com/bdancer/blender-for-vray/commit/1b7e2a39e4a88b5e66a9bee1b5c74423defba015. Builds are getting compiled.

**Comment by JuhaW** [comment]
Thats nice, I hope Win build are also there :)

**Comment by JuhaW** [comment]
Okey, I noticed its in exporter part, thanks.

**Comment by bdancer** [comment]
@JuhaW it's in both parts =) Build will be ready today, need to fix upload at my build machine...

**Comment by pietruh00s** [comment]
Thanks for adding this despite the fact that probably it isn't the most important thing in your schedule. :)
