### ISSUE TITLE
Isn't the preview mapping to big?

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#142]
Is there any way to scale down mapping only on preview objects?

![prev1](https://cloud.githubusercontent.com/assets/11031197/12356953/a1ffae58-bba5-11e5-8963-fbf93f34e05c.JPG)
![prev3](https://cloud.githubusercontent.com/assets/11031197/12356958/a6461632-bba5-11e5-8f17-8cbfd7045e25.JPG)

Also why mapping on a cube is moved?
![prev2](https://cloud.githubusercontent.com/assets/11031197/12357022/049de2f0-bba6-11e5-9991-1f81365c0c14.JPG)

**Comment by bdancer** [comment]
You could create your own preview scene and do whatever you need.
Use this file as an example https://github.com/bdancer/vb30/blob/master/preview/preview.blend then save it as to <BlenderUserConfigDir>/<BlenderVersion>/config/vrayblender/preview.blend

**Comment by pietruh00s** [comment]
Thank you! I'll try :)
