### ISSUE TITLE
V-Ray doesn't see textures packed into a Blender file

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#149]
![pack-into-blend](https://cloud.githubusercontent.com/assets/9629577/13881623/e5648bac-ed21-11e5-8a2f-29f038ca90c0.png)

1. Pack all files into .blend
2. Remove textures from selected locations / move the file to another computer / move textures to other locations / rename textures 
3. Render scene

V-Ray replace texture with a solid black color.

**Comment by bdancer** [comment]
This will never be supported - V-Ray is a separate running process.
You'll have to unpack files before render.
