### ISSUE TITLE
Saving output

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#150]
Windows versions from 17 & 18 march have problems with saving renders.

This might be helpfull:
![4](https://cloud.githubusercontent.com/assets/9629577/13899330/df019cc6-edeb-11e5-87c2-c264162c9038.jpg)

1. This options make blender crash:
![1a](https://cloud.githubusercontent.com/assets/9629577/13899332/e275ec04-edeb-11e5-841a-390e476bd983.jpg)
![1b](https://cloud.githubusercontent.com/assets/9629577/13899334/e6b5f930-edeb-11e5-800d-c61a93736d31.jpg)

2. This options create folders, but don't save renders
![2](https://cloud.githubusercontent.com/assets/9629577/13899338/fb6b9fce-edeb-11e5-831a-b55561e751a5.jpg)

3. The main render (RGB color) saved directly from V-Ray Standalone is black
![3](https://cloud.githubusercontent.com/assets/9629577/13899339/1dfda4ba-edec-11e5-955e-a61bfa561244.jpg)

---
How to save a material ID mask? I can't find the proper node in Render Channels in latest builds.

**Comment by bdancer** [comment]
# Fixed.
# Can't reproduce
# Can't reproduce

> How to save a material ID mask? I can't find the proper node in Render Channels in latest builds.

Don't understand. Which mask? Render channel? It'll be saved along with other render channels.

**Comment by kasperski95** [comment]
2.& 3. I'll try to reproduce again when, there will be a new build on nightlies.chaosgroup.com. Maybe the fix solved these issues.

> Don't understand. Which mask? Render channel? It'll be saved along with other render channels.

Previously, there was _Material ID_ option in _Color Channel_ node.
![matid](https://cloud.githubusercontent.com/assets/9629577/13915554/c476a1e2-ef55-11e5-9ab5-fa5ec1379448.jpg)

It generated material masks, based on color chose in the material node editor.
![a](https://cloud.githubusercontent.com/assets/9629577/13915840/4b78ca98-ef57-11e5-983d-503317aeec29.jpg)

but in the latest build, I can't find it
![withoutmatid](https://cloud.githubusercontent.com/assets/9629577/13915726/b155e482-ef56-11e5-8a7b-bd4877365369.jpg)

**Comment by bdancer** [comment]
> Previously, there was Material ID option in Color Channel node.

Thanks! Fixed with https://github.com/bdancer/plugins_desc/commit/648ca441ba9c5047254f26809a598aad9bbd7d69.

**Comment by kasperski95** [comment]
2 & 3 & material ID fixed, but 1 still makes Blender crash. Variables _%C_ or _%F_ in _Filename_ or _Path_ cause the problem. Also variable %S generates random numbers instead of scene name.

**Comment by bdancer** [comment]
@kasperski95 tnx! Fixed with https://github.com/bdancer/plugins_desc/commit/27930bacf73504865a59ea13a9e5a0e7ad9e00db. When changing plugins to JSON I forget to change variable marker from "%" to "$".

> Also variable %S generates random numbers instead of scene name.

It's not random actually =) You could use any variable from here: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

**Comment by kasperski95** [comment]
Thanks, works perfectly.
