### ISSUE TITLE
Make All paths relative doesn't work with V-Ray proxies

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#151]
![1](https://cloud.githubusercontent.com/assets/9629577/13914367/312a7460-ef4e-11e5-8fde-1a411dbac53f.jpg)

_Make All paths Relative_ and _Make All paths Absolute_ don't affect paths of V-Ray proxies.

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/blender-for-vray/commit/842478ac9d8c939517d2fa8adc6304ce33ca0810

**Comment by kasperski95** [comment]
Thanks
