### ISSUE TITLE
vb30: 2.77 don't render saved scenes

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#152]
I just downloaded blender 2.77 with vray additions and I couldn't render any saved scenes. I tested and I can render default scene. Also when I choose override material and change place to saved file I get loose this material. Can someone confirm this?

Previously I used blender 2.76. I installed python 3.5.1 and reinstall blender 2.77 one more time. When I installed 2.76 again, all work fine.

**Comment by bdancer** [comment]
I could not confirm any of this. Could you send me broken scenes?

**Comment by kontrolermpl** [comment]
I read one more my post and I didn't write, that I can't render with 2.77 any scenes saved with 2.76. Can you check it? Everything is al right, but when I put F12 Blender crush.

**Comment by bdancer** [comment]
I just did it. No crash.

**Comment by kontrolermpl** [comment]
O.K. so I will reinstall blender and clean it from disc, and try again. I think, that something is with my system (I use windows 10), because this problem affect all scenes.

**Comment by bdancer** [comment]
That's weird, anyway send me some scene just in case.

**Comment by kontrolermpl** [comment]
[STUDIO_soft_area.zip](https://github.com/bdancer/blender-for-vray/files/186039/STUDIO_soft_area.zip)

Please.

**Comment by bdancer** [comment]
No crash, try newer build may be.

**Comment by kontrolermpl** [comment]
O.k. I'll try it and give you feedback.

**Comment by bdancer** [comment]
May be it's related to the latest fix from here https://github.com/bdancer/blender-for-vray/issues/150#issuecomment-199318557, so try updating.

**Comment by kontrolermpl** [comment]
Work fine for me with latests (today)  build. Thx!
