### ISSUE TITLE
vb30: Subdivision for glossy reflection

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#153]
Hi,

In my last build "subdivs for glossy reflect" parameter has no effect on Preview.
I put there value 256 and material is still noisy - for example ward BRDF and glossy = 0,8

Can you check it?

**Comment by bdancer** [comment]
Is "Use local subdivs" turned on under "DMC Sampler"? If not then this is how it works. It's a new V-Ray 3.x feature, when "Use local subdivs" is off *all* subdivision controls are ignored and V-Ray will adjust subdivs automatically.

**Comment by kontrolermpl** [comment]
O.K. so I picked it and change local subdivision and Preview material is showing, that nothing change.

![subdivision_error](https://cloud.githubusercontent.com/assets/8292526/14045516/362b4b1a-f29b-11e5-874f-1194fdccd8e0.jpg)

**Comment by bdancer** [comment]
Preview uses very low settings for AA. Check the actual render.

**Comment by kontrolermpl** [comment]
I know, that final render is O.K., but I thought, that this will be work, like in previous builds. But all right, I must accustom with this how it works now (but in my opinion before was better, to see how glossy reflection look like at the moment in preview picture) . Thank for quick answer.
