### ISSUE TITLE
'Remap Relative' affects name of UV in 'Image File' node

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#155]
How to reproduce the issue:
1. Open Blender
2. Add an object and create UV map
3. Add a material
4. Add an Image Node
5. Choose UV for an Image Node
6. Save the file

or

1 + 6 + 2 + 3 + 4 + 5 + Save in a different localization

![issue](https://cloud.githubusercontent.com/assets/9629577/14052071/afaf2d9a-f2c7-11e5-8ee0-25836783b63d.png)

**Comment by bdancer** [comment]
Nice bug =) Will fix on Monday.

**Comment by bdancer** [comment]
Sorry for the delay, this issue is a bit trickier then I thought. Will try to fix asap.

**Comment by kontrolermpl** [comment]
I must add, that this happened too with auto save render. I have picked Output in Render panel with this parameters:

Path: //render/$F/
Filename: $F

When I save file in any place I get this:

Path: //render/$F/
Filename: //..\.\..\$F

And now Vray don't render.

**Comment by bdancer** [comment]
Fixed with: https://github.com/bdancer/blender-for-vray/commit/b1cf519a62dc46929a3d9926ffd5daec1cc78f68
Builds are cooking...

**Comment by kontrolermpl** [comment]
It works very well, thank you!

**Comment by kasperski95** [comment]
Thanks.
