### ISSUE TITLE
vb30: Random Shading Values doesn't work

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#156]
Hi,

I usually use this:
https://cloud.githubusercontent.com/assets/319784/3675148/c8f4bcfc-127c-11e4-89f2-e0ddeafed6ec.png
to get random shading, but with build vrayblender3-2.77-b1cf519-x86_64-windows vray get only color on the right side from remap texture.

[Tiles_randomize_color_TEST_v01.zip](https://github.com/bdancer/blender-for-vray/files/207819/Tiles_randomize_color_TEST_v01.zip)

**Comment by bdancer** [comment]
Use "Gradient Ramp" in "Position" mode for now:
![vb30_gradient_ramp_random](https://cloud.githubusercontent.com/assets/319784/14350693/88688374-fcd3-11e5-837e-452d6d685993.png)

**Comment by kontrolermpl** [comment]
Thank you for temporary tip.

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/plugins_desc/commit/45c51f4998aad1bca194b12aaab031205ca90ec7. Recreate Remap node or set "Input Max Tex" from 0.0 to 1.0.
