### ISSUE TITLE
vb30: Proxy destination folder

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#157]
Hi,

When I copy blend file with proxy generation folder (//proxy) from example C:\folder1\folder2\proxy for example to disc D:\ , then vray search proxy with complete access path ( c:\folder1\folder2\proxy ) instead of //proxy . Of course in blender I have this path //proxy .

**Comment by kontrolermpl** [comment]
bdancer, can you fix this?

**Comment by bdancer** [comment]
I'm actually can't reproduce this...

**Comment by bdancer** [comment]
Ok, I think I got it, fixing.

**Comment by kontrolermpl** [comment]
Thank you!

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/vb30/commit/bd0cb6029216ea057627885c46ab4b8f477144e4
