### ISSUE TITLE
Remap node issue

### ISSUE THREAD

**Issue by Zaurio** [bdancer/blender-for-vray#161]
The modified remap node seems doesn't work as before.

**Comment by bdancer** [comment]
Duplicate of https://github.com/bdancer/blender-for-vray/issues/156

**Comment by Zaurio** [comment]
why duplicate? i meant, remap node doesnt work at all in 2.77 latest build

**Comment by bdancer** [comment]
Because issue #156 is also about broken Remap node.

**Comment by Zaurio** [comment]
oh, sorry for misunderstanding) i messed that page with another issue.

**Comment by bdancer** [comment]
@Zaurio no worries, I've basically added comment about duplicate only for myself =)

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/plugins_desc/commit/45c51f4998aad1bca194b12aaab031205ca90ec7. Recreate Remap node or set "Input Max Tex" from 0.0 to 1.0.
