### ISSUE TITLE
VB30: Samplerate works only with Progressive sampler type.

### ISSUE THREAD

**Issue by witaj** [bdancer/blender-for-vray#163]
Hi Andrei

It seems that samplerate render element works only with progressive sampler type.
I will be glad if you can fix that.

Thank you and cheers.

**Comment by bdancer** [comment]
Turn on "Consider For AA" - should work.

**Comment by witaj** [comment]
I did what you suggest but it still returns black.

**Comment by bdancer** [comment]
@witaj sorry, my mistake - enable "Filtering".

**Comment by witaj** [comment]
yey, it works. Thank you.
