### ISSUE TITLE
vb30: Dispalcement does't work

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#166]
Hi,

I'm using "vrayblender3-2.77-997b5e4-x86_64-windows.exe" and before I used "vrayblender3-2.77-f25c814-x86_64-windows.exe" . My problem is, that displacement geometry don't work any more. I use procedural vray texture like smoke and noise - any effect.
Here is my blend file:
[Displacement_TEST_01.zip](https://github.com/bdancer/blender-for-vray/files/292999/Displacement_TEST_01.zip)

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/blender-for-vray/commit/fd34178b97d2697e83d0d73aaecd2bfa304d28da and https://github.com/bdancer/plugins_desc/commit/3c94bc06dd554c24fbaaafcb97e88261e0416527.

**Comment by kontrolermpl** [comment]
Thank you for quick fix! Regards!
