### ISSUE TITLE
Node groups

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#167]
Problem occurs when there are 2 or more the same node groups in one material tree.

![1](https://cloud.githubusercontent.com/assets/9629577/15927711/7c58b9e0-2e43-11e6-98bc-ebeaa0263787.jpg)
![2](https://cloud.githubusercontent.com/assets/9629577/15927713/7d2a4d5c-2e43-11e6-9b96-fe3740639a13.jpg)

_________
Also the node "Blend" has slider which value is limited from -100 to 100 (should be from 0 to 1).

**Comment by bdancer** [comment]
1. Could you pls upload a scene?
2. I'll check if it's possible to add limits to those sliders.

**Comment by kasperski95** [comment]
[node group issue.zip](https://github.com/bdancer/blender-for-vray/files/306965/node.group.issue.zip)

___
(Is it possible to control fresnel reflections using a curve? V-Ray in 3ds max has curve in falloff node.)

**Comment by bdancer** [comment]
Thanks for the scene.

> Is it possible to control fresnel reflections using a curve?

Check this topic: http://forums.chaosgroup.com/showthread.php?79483-Fresnell-Curves/page5

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/blender-for-vray/commit/2aa05e4458082dc243aabb22d598b7eec86a029b. Builds are in progress.

**Comment by kasperski95** [comment]
Thanks
