### ISSUE TITLE
Compatibile V-Ray version

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#168]
Which v-ray is compatibile (best to use) with last nightly relases (for eg vrayblender3-2.77-2aa05e4-x86_64-windows)?

**Comment by bdancer** [comment]
Any V-Ray version is compatible, but exporter tries to utilize all latest V-Ray additions. I could recommend using nightly builds.

**Comment by bdancer** [comment]
By mean compatible I mean that exporter generates a vrscene file with the scene description any V-Ray could read; of course if some new plugins are missing in older versions they will not work (like missing shader plugins will render black).

**Comment by pietruh00s** [comment]
Using V-Ray for Maya 3.0 in the same scene opened in 2.77 and 2.76 renders  totally different. Also some nodes and settings behave wierd (need to change values, node position, some nodes from 2.77 do nothing)... So I stuck on 2.76...
