### ISSUE TITLE
Triplanar Node Input Sockets

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#172]
Would be possible to add a scalar input socket for "Scale" and "Blend" of the Triplanar texture node?
Sometimes you have to create multiple Triplanar nodes (Diffuse, Bump, Reflection), and with this input sockets would be easier to sync their settings globally by a single scalar node.

![triplanar](https://cloud.githubusercontent.com/assets/338739/16272697/2d509fde-3875-11e6-8a67-c4f772e465e2.jpg)

**Comment by cyberlecs** [comment]
This is a mockup of the proposed modification:
![triplanar](https://cloud.githubusercontent.com/assets/338739/21293445/e4144d7e-c50b-11e6-98ec-bdf42ede3cba.jpg)

This way you can use a single user scalar node to control multiple instances of the triplanar node (color, reflection, bump, ...) without having to update them manually one by one.

**Comment by bdancer** [comment]
Well, I'll have to create some "value" nodes for that since "User Scalar" will not work in this case, but it's doable.

**Comment by JuhaW** [comment]
One way to do it is to add group, Triplanar node and use the same group for diffuse, bump, reflection etc. When you change Scale or Blend, then they are all synced.

**Comment by cyberlecs** [comment]
Just sharing a solution for this:
You can use a Transform node to control the scale of multiple Triplanar nodes.
With Invert option on is even better, because you can use real world units.

![triplanar](https://cloud.githubusercontent.com/assets/338739/24254916/da0755f4-0fc2-11e7-9de8-42e64ba136c4.jpg)
