### ISSUE TITLE
Nightlies builds Blender issue

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#174]
Builds from nightlies.chaosgroup.com crash, when objects with array modifier are duplicated.

**Comment by kasperski95** [comment]
The build 13c0ed0 from 10 August works fine but the newest version - 19e2c7d contains this issue.

**Comment by poseidon4o** [comment]
This should be fixed after e03d2640b7cd55aa8436d045df257d37c66e9408
