### ISSUE TITLE
Modifier Settings form Physics Tab are mising

### ISSUE THREAD

**Issue by coolerinc** [bdancer/blender-for-vray#180]
After setup Smoke in Blender Internal and switching back to V-Ray - settings dissapear
https://i.gyazo.com/4e42b7c348a2c36e55ff63d3fd661506.png
https://i.gyazo.com/0e304667831314273d15afbd70a74ced.png

**Comment by bdancer** [comment]
Fixed with: https://github.com/bdancer/vb30/commit/0ef6795711864c128e1184ae5fd4f08d9c516aec
Please, check if it works for you.

**Comment by coolerinc** [comment]
Everything is ok now! Thx
