### ISSUE TITLE
Material node => Material (issue when linking)

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#182]
When material nodes are linked and another blend file is opened without closing Blender, material nodes are assigned to wrong materials. It happens randomly and I couldn't find all factors of this issue.
[issue.zip](https://github.com/bdancer/blender-for-vray/files/601593/issue.zip)

**Comment by kasperski95** [comment]
Build from 20.11 doesn't store information about material and material nodes at all.

**Comment by bdancer** [comment]
Should be already fixed with https://github.com/bdancer/blender-for-vray/commit/29865fc08c255ca2db6c75abccef2a5daf9ca7f0.
