### ISSUE TITLE
2 different material nodes linked from 2 different files + material nodes have the same name

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#183]
A file 'A' has a material node 'X', and a file 'B' has a different material node but also named 'X'.
Issue occur in a file C, when both of these materials are linked to common file.

Update:
There is even a bigger problem. If 2 group instances are linked to the same file, and an object within first group instance has the same name as another object in second group instance, one of these two won't be visible during rendering.

**Comment by bdancer** [comment]
Could you post a scene so I could check the exact setup?

**Comment by kasperski95** [comment]
[issues.zip](https://github.com/bdancer/blender-for-vray/files/604730/issues.zip)

**Comment by bdancer** [comment]
Thanks, fixing...

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/blender-for-vray/commit/8c1350a0ee0d3a027c38665e8b683e10141d661a and https://github.com/bdancer/blender-for-vray/commit/a6c87b97abc896f9956dad336af921acd0215f1a.
