### ISSUE TITLE
Import Error: No module named 'vb30'

### ISSUE THREAD

**Issue by starantino** [bdancer/blender-for-vray#185]
Blender Version: 2.76b
OS: Linux-Ubuntu 16.04
Blender for vray plugin: vb30

When I try to enable addon I am getting this error and cannot activate:
![screenshot from 2016-11-21 12-40-52](https://cloud.githubusercontent.com/assets/13489240/20493907/a7af3a2a-afe8-11e6-96cb-384f855e6af2.png)

**Comment by starantino** [comment]
Doing the same thing in OS X El Capitan.

**Comment by bdancer** [comment]
You need a special build of Blender, add-on doesn't work with a regular Blender build.
Download it at https://nightlies.chaosgroup.com/#/blender.

**Comment by starantino** [comment]
Tried accessing and there were no files in any of the directories.

**Comment by bdancer** [comment]
@starantino, pls write to support@chaosgroup.com.
