### ISSUE TITLE
vb30: Softbox texture

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#187]
Hi,

In texture soft-box circle shape option disappear. Can you fix it? Mu build is vrayblender3-2.78-52a2fdc-x86_64-windows .

![softbox_bug](https://cloud.githubusercontent.com/assets/8292526/20700305/d55c8fb6-b60c-11e6-928c-ead644e48bbe.jpg)

P.S. Thank you for remove bug of material linking.

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/plugins_desc/commit/8da2a6e304c74050ebc93637728f322d0433e1f8.

**Comment by kontrolermpl** [comment]
Thanks a lot!
