### ISSUE TITLE
Object node tree + Linking

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#189]
If an object node tree is linked, after reloading a file, the node tree is no longer connected to the object.

**Comment by bdancer** [comment]
Linked like library linking? So, you are linking only the tree not the object?

**Comment by kasperski95** [comment]
I linked an object with a node tree. Then I made the object local. The node tree however was still linked. After reloading the file, the node tree was no longer connected to the object. If I made the node tree local, everything worked fine.

**Comment by bdancer** [comment]
Ok, we need to write some code to make linked ntree local when making the object local.

**Comment by poseidon4o** [comment]
We added a possible fix for object node tree to be made local. You can test with latest nightly builds.

**Comment by kasperski95** [comment]
Still it doesn't work:
![ezgif com-0eabf0068c](https://cloud.githubusercontent.com/assets/9629577/21241748/78cedc06-c311-11e6-8bfe-95ed58bcc843.gif)

**Comment by poseidon4o** [comment]
That UI option was missed. It should work in latest nightly builds.
