### ISSUE TITLE
Group instances + Random by render ID

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#190]
https://github.com/bdancer/blender-for-vray/issues/114

I think this the same problem however there is no "Use Instancer for dupli/particles" option in the latest build.

**Comment by cyberlecs** [comment]
+1
"Use Instancer for dupli/particles" option is gone in recent builds.

**Comment by bdancer** [comment]
I'll have to fix this on V-Ray level. Hope it won't take too much time.

**Comment by bdancer** [comment]
I've made some additions to V-Ray, you need some latests nightly builds. Pls, check if it works for you.

**Comment by kasperski95** [comment]
Where can I download the V-Ray Standalone nightly build from?

**Comment by bdancer** [comment]
@kasperski95 https://nightlies.chaosgroup.com/#/vraystd3 if you don't have access write to support.
