### ISSUE TITLE
Group node + node tree changed = incorrect sockets

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#192]
Group node + node tree changed = incorrect sockets:
![issue](https://cloud.githubusercontent.com/assets/9629577/21083052/492f2c70-bfe8-11e6-8d98-674776891ab9.gif)

----------------------------------------
If this button is pressed, Blender should automatically update node tree in the material tab. Currently this button gives no feedback.
![1](https://cloud.githubusercontent.com/assets/9629577/21083053/4bfdc3bc-bfe8-11e6-9f74-7cc136c22813.jpg)

**Comment by bdancer** [comment]
Group node is a native Blender node. May be it'll be fixed. I'll sync the sources with Blender's master.
