### ISSUE TITLE
vb30: BUMP standard material doesn't work

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#199]
Hi,

I just use bump intensity socket connection in Standard material node and it doesn't work. Instead of it I use color socket, but I have to change it in all material nodes... Can you fix it? My build is vrayblender35-2.78-b138d20-x86_64-windows updated 2017-01-16.

Regards!

**Comment by bdancer** [comment]
Try today's nightly pls.

**Comment by kontrolermpl** [comment]
And it works fine now, thx bdancer!
