### ISSUE TITLE
Image filter options missing in progressive mode

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#200]
Would be nice to have image filter working in Progressive mode too (like it works in Max).
In Blender it workis fine in "Adaptive DMC" or "Fixed" sampler modes, but you change the sampler type to Progressive, image filter dialog is missing.

Forum thread: http://forums.chaosgroup.com/showthread.php?91884-Image-filter-option-in-progressive-mode

![01imagefilter_max](https://cloud.githubusercontent.com/assets/338739/22036951/75c753aa-dcdc-11e6-8116-efa8505c8d59.jpg)

![02imagefilter_blender-fixed](https://cloud.githubusercontent.com/assets/338739/22036956/7780c4ba-dcdc-11e6-82c6-3d8330919c3d.jpg)  ![03imagefilter_blender-progressive](https://cloud.githubusercontent.com/assets/338739/22036958/7964f8d2-dcdc-11e6-9db0-c4fa5629be30.jpg)

**Comment by bdancer** [comment]
Fixed with https://github.com/bdancer/vb30/commit/cc5f717a03f8eb6682d1891a37beb9c4836a3b1d.

**Comment by cyberlecs** [comment]
Thanks!
