### ISSUE TITLE
Output node limitation

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#201]
Some options of the texture "Output Node" are not working as expected.
"Output Mult", "Color Mult" and "Color Offset" are displayed as color fields limited to 0-1 range.
In Max, their equivalent fields "Output Amount", "RGB Level" and "RGB Offset" are numerical and not limited to 0-1 range.

This node has many potencial uses (eg: adjusting brightness and constrast), but with its range limited to 0-1 make it a bit useless.

Forum thread: http://forums.chaosgroup.com/showthread.php?92014-Output-node-limitation

![color_output_node](https://cloud.githubusercontent.com/assets/338739/22037443/4ddc1086-dcde-11e6-9fd3-1c7d7a9226c5.jpg)

**Comment by bdancer** [comment]
I've pushed some changes, build will be ready tomorrow.

**Comment by cyberlecs** [comment]
Thanks, all fine now! =)
