### ISSUE TITLE
hair sampler doesn't work

### ISSUE THREAD

**Issue by coolerinc** [bdancer/blender-for-vray#202]
In build f000775 (10.03.2017) hair sampler doesn't work
I compared it to d804fac (18.10.2016)

**Comment by coolerinc** [comment]
test scene http://pasteall.org/blend/index.php?id=45929
should look like this https://i.gyazo.com/f554ff8d444056694005cb719474a611.png

**Comment by bdancer** [comment]
I've installed today's build, works fire for me.

**Comment by poseidon4o** [comment]
This should be resolved with this [commit](https://github.com/bdancer/plugins_desc/commit/d6d8a5f07686c36d8bcc910b6c5c91b5c247cf1f).
It will be included in next nightly or you can update exporter to get it now.
