### ISSUE TITLE
Viewport Shading Textured doesn't work

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#206]
When unwrap and add texture there is no preview in the viewport when textured shading is
 enabled like in older builds

![capture2](https://cloud.githubusercontent.com/assets/11031197/24040631/492e3e92-0b0a-11e7-9ff3-f5534166a674.JPG)

Tested on windows build:  2.78-d601a30, 2.78-35c70e0, 2.78-fdc7c5e

**Comment by poseidon4o** [comment]
If you double click on the "Image File" node in the node tree, the image from it should be applied in Texture viewports.

**Comment by pietruh00s** [comment]
No matter how many times I clicked, the texture still doesn't show in the viewport... :(

**Comment by cyberlecs** [comment]
@pietruh00s, this method just works in object mode. (in edit mode nothing happens)
