### ISSUE TITLE
Random light color

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#207]
I can't make it to work... This node setup is attached to few spots, but they use only first color from remap node...

![random_lights](https://cloud.githubusercontent.com/assets/11031197/24208465/f21df282-0f23-11e7-99ee-683ffc2e8679.JPG)

**Comment by bdancer** [comment]
By "Spots" you mean spot lights? Only Area, Sphere and Mesh lights has render ID so this will not work for another types.
