### ISSUE TITLE
Normal map

### ISSUE THREAD

**Issue by Inwermitodion** [bdancer/blender-for-vray#210]
Something strange happens when rendering Normal maps. This is a comparison from the same scene but on other versions of Blender vray. The first render A was made as: date 20170124_ok vrayblender35-2.78-cb49ffa-x86_64-windows.zip while render B: vrayblender35-2.78-9eaf9a7-x86_64-windows.zip.
![przechwytywanie](https://cloud.githubusercontent.com/assets/8227927/25106387/7d38d35a-23c9-11e7-82a5-7b633056e170.PNG)

**Comment by Inwermitodion** [comment]
Colors also changed a bit for the same scene but rendered in the other versions of Vray Blender. Time also changed the rendering which is a huge plus.

**Comment by poseidon4o** [comment]
@Inwermitodion can you please upload a test scene that reproduces the issue?

**Comment by Inwermitodion** [comment]
Hi, I downloaded the latest version from today: vrayblender35-2.78-583e9f0-x86_64-windows.zip 230 MB 19 Apr 19:32 and I can see from this version that it is ok. I noticed yet from the last installed version (vrayblender35-2.78-9eaf9a7-x86_64 -windows.zip) that when I wanted to upload a test scene with this problem and moved the scene to the desktop. Suddenly, vray started rendering properly. So I think you can close this Issue.
