### ISSUE TITLE
Very slow delete speeds on blender for Vray builds

### ISSUE THREAD

**Issue by kirompower** [bdancer/blender-for-vray#212]
Deleting objects in the blender for Vray builds is extremely slow compared to the standard blender (no Vray).
Here is a video showing what I mean:
http://dox.bg/files/dw?a=119ba5e35b
For this particular example:
blender = ~4 seconds
blender for Vray = ~ 180 seconds

And it doesn't matter if it is geometry, it is slower even when deleting cameras.

**Comment by poseidon4o** [comment]
@kirompower any chance you could send us the scene? Can you reproduce this with other scenes and other platforms? And also what is your ubuntu version?

**Comment by kirompower** [comment]
Ununtu is 16.04 LTS and I have sent a download link of the scene to Andrei's skype, because here on github there is no PM

**Comment by kirompower** [comment]
@poseidon4o did you get the scene from Andrei, because the link may expire soon ?

**Comment by kirompower** [comment]
Still working on the problem ?

**Comment by bdancer** [comment]
@kirompower Yes, Kiro, sry for delay, hope to fix this soon.

**Comment by poseidon4o** [comment]
@kirompower we have sped up the deletion of multiple objects with 0a0244790946de07b9df2ba536ba23a5aedbdf43 The change will be included from next nightly build.
