### ISSUE TITLE
Stereo mode doesn't work. 

### ISSUE THREAD

**Issue by michax** [bdancer/blender-for-vray#215]
I've enabled stereo mode in general render settings and also enable stereoscopic setting in camera. However I don't get side be side output in latest version of vrayblender (2.78-c3d7685-x86_64-windows) and vray (35004_x64_vc11_hwlic). 

In previous version I was able to render stereo images without any problems (side by side stereo).

Did something change that requires one more option to enable side by side stereoscopic output?

**Comment by michax** [comment]
I've also went back one version to 2.77 (Hash: 8141c15). This version supports stereo without any problems.

**Comment by michax** [comment]
After further investigation, as expected scene_camera.vrscene misses following entries:

```
RenderView LeftCam {
	transform=TransformHex("39E8403F3F4B283F179345360DBC92BE4E31A83EAD64663FB975173F8F9C2DBF1534DF3E00000000000000A0FAF906400000004035AB02C0000000A0E30A0340");
}

RenderView RightCam {
	transform=TransformHex("39E8403F3F4B283F179345360DBC92BE4E31A83EAD64663FB975173F8F9C2DBF1534DF3E00000000000000804A5E0740000000E0B15302C0000000A0E30A0340");
}
```

**Comment by bdancer** [comment]
@michax tnx for the investigation! We'll fix this asap.

**Comment by poseidon4o** [comment]
@michax this should start working with next nightly build

**Comment by michax** [comment]
@poseidon4o Thanks! Will check it tomorrow.

**Comment by michax** [comment]
Ok, so it looks like we are close to finish line, but we are missing 'second eye'.

![Result](http://animuj.com/lab/vray/stereo-issue-2.78-nightly.JPG)

So now It looks like only one of two stereo cameras is outputting result. Also it looks like perspective for it is wrong.

I've packed all my vrscene files. LeftView and RightView are now present, however it looks like we are missing something else. 
http://animuj.com/lab/vray/vrayblender_standalone.zip

**Comment by poseidon4o** [comment]
@michax can you please upload the blend file you are testing with?

**Comment by michax** [comment]
@poseidon4o Sure, here it goes:
http://animuj.com/lab/vray/stereo-simple.blend

**Comment by poseidon4o** [comment]
@michax seems I forgot to push the update in the python exporter. You can use "Update Exporter" from the System tab or wait for next nightly and the scene should render correct.

**Comment by michax** [comment]
Works great now, thanks.
