### ISSUE TITLE
Artifacts when baking with Irradience map

### ISSUE THREAD

**Issue by michax** [bdancer/blender-for-vray#218]
Hi,

With latest version of blender (b9008f4), I noticed that baking with Irradiance Map is broken. I get lot's of artifacts, and precision of Irradience map seems to be static, despite changing subdivision min/max.

Camera View: 
![Image](http://animuj.com/lab/arch-baked/scene-map.PNG)

Baked View:
![Image](http://animuj.com/lab/arch-baked/baked-map.PNG)

I tried changing around interpolation types and lookup methods. But I only got worst results.
Baking previously worked without major problems with default Irradiance Settings.

File for revision:
http://animuj.com/lab/arch-baked/simple-scene.zip

Above issues occur whenever I pair Irradiance Map with Brute Force or Light Cache.

**Comment by michax** [comment]
In addition, Light Cache takes now forever to finish when Baking. It takes around 40s to finish for simple scene, when before it was almost immediate.

**Comment by michax** [comment]
I've checked same scene against 2.77 default GI settings (Irradiance + Light Cache). Whole scene renders in 11s, Light Cache takes around 0.7s. No artifacts. 

![Good](http://animuj.com/lab/arch-baked/scene-good.PNG)

**Comment by poseidon4o** [comment]
@michax this should be fixed with latest nightly.

**Comment by michax** [comment]
Thanks. Will check today.

**Comment by michax** [comment]
Works great. Thanks!
