### ISSUE TITLE
vb30: Softbox texture fail

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#221]
Hi there,
I've problem with softbox texture for plane light problem. I know, that this texture has changed some time ago. I think, that the old one was better. There's no different, that I use new or old, this strange behaviour still appear.
1. Alpha channel choosing color for gradient doesn't work, so I must use old softboxtexture. Make copy and connect intensity to Alpha Mult socket.
2. There's some shifting for radial vignette
3. V Vignette gradient get result only for half of light height

I attach bend file.
[SoftBoxTexTESTv01.zip](https://github.com/bdancer/blender-for-vray/files/1154660/SoftBoxTexTESTv01.zip)

Can you check it? I need it to final of my job.
P.S. Great work, REGARDS!

**Comment by poseidon4o** [comment]
@kontrolermpl this should start working from tomorrow's nightly. For today you can attach explicit channel mapping to TexSoftbox and it will work as it should.
