### ISSUE TITLE
Bug while enabling addon

### ISSUE THREAD

**Issue by mohasher** [bdancer/blender-for-vray#225]
This happens when I try to enable the vray addon , this happened with nightly builds from 30-8-2017 to 5-9-2017

![screenshot at 2017-09-05 14-40-18](https://user-images.githubusercontent.com/25725235/30061602-49404f72-9248-11e7-8544-e494f39f6e9e.png)

**Comment by bdancer** [comment]
1. Do you have a separate copy of the add-on at `.config/blender/2.79/scripts/addons`? Build is already shipped with the exporter addon.
2. Any particular reason to run Blender as superuser?

**Comment by mohasher** [comment]
I tried to delete the copy at .config folder didn't work too , it for some reason always makes a copy there  when I try to enable it .

The build itself cant enable the exporter addon , so I tried to run as super user thinking it might be a permissions error , but it isn't .

The previous version worked fine

**Comment by mohasher** [comment]
I work in ubuntu , I used the bin prepared for centos , does this have any effect ??

**Comment by bdancer** [comment]
@mohasher if it runs then in doesn't matter.

**Comment by mohasher** [comment]
I am thinking of migrating to a blender - vray workflow in ubuntu , so I am trying to optimize it . If you have any question or  anything in mind that could help find the bug tell me ( even if remote access is needed )

**Comment by bdancer** [comment]
@mohasher sure, please, write me at andrei.izrantcev@chaosgroup.com about the remove access.

**Comment by bdancer** [comment]
Re-installation + cleaning the .config directory fixed the issue.
