### ISSUE TITLE
vb30 Error: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Seliverstoff** [bdancer/blender-for-vray#228]
Я сомневаюсь, что это проблема vb30, но заметил, что в Internal работает немного стабильнее.
На всякий случай опишу проблему.
Довольно большой файл, много объектов, но бывали и больше. Неделю спокойно работал с этим файлом, всё шло хорошо. Шла работа по оптимизации (создание линковки между объектами, улучшение сеток, создание UV), новые объекты не создавались. Неожиданно стала появляться эта ошибка. Чтобы открыть файл, надо отключить загрузку UI и включить режим отображения BoundingBox. Потом оставить только один слой (3) и перейти в режим Solid. Так можно работать какое-то время, но в любой момент снова будет крах. Иногда получается включить сразу все слои, но не на долго.
Пробовал работать на MAC OS, результат тот же. Сейчас Win10.

**translate.google**
I doubt this is a vb30 problem, but noticed that the Internal works a bit more stable.
Just in case I'll describe the problem.
Quite a large file, many objects, but there were more. A week worked quietly with this file, everything went well. There was work on optimization (creating link between objects, improving grids, creating UV), new objects were not created. Suddenly, this error began to appear. To open the file, you must disable the UI boot and enable the BoundingBox display mode. Then leave only one layer (3) and go to Solid mode. So you can work for a while, but at any moment there will be a collapse again. Sometimes it turns out to include all layers at once, but not for long.
I tried to work on MAC OS, the result is the same. Now Win10.

[Problem File](https://drive.google.com/file/d/0B1O7_4EHkspmQi03bmxRa3docnc/view?usp=sharing)

**Comment by bdancer** [comment]
The file is corrupted and this causing the crash in mesh drawing code.
