### ISSUE TITLE
Trouble with blender linux 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by julvvvv** [bdancer/blender-for-vray#235]
HI ,

I run on Version 16.04.3 LTS (Xenial Xerus) 64-bit , Noyau Linux 4.4.0-112-generic x86_64.
Update my depot after fresh install.
apt-get install gcc-4.9 g++-4.9, git, ninja, python 3 ok
place plug vb 30 ok .. i see your plug but no run.
[screenshot at 2018-02-09 10 27 36](https://user-images.githubusercontent.com/19374263/36021710-f01879b4-0d86-11e8-84d7-a66dfcc23303.jpg)

It's obligation to run with old ubuntu 12.04?
Great staff for your support.
king regard;
rink

**Comment by bdancer** [comment]
I can't open this screenshot, it shows nothing.
1. Have you installed Blender build from https://nightlies.chaosgroup.com/#/blender ?
2. Have you installed V-Ray Standalone?
3. Could you upload your screenshot ones again?
4. Any errors in console?

**Comment by julvvvv** [comment]
hi ,


i donwload this version from chaosgroup , vraystd_trial_36004_linux_x64_gcc-4.4_hwlic_utf8


and plugg vb3master.zip from git


[cid:393ebfeb-a6fc-4011-90c6-bb646bc035de]



________________________________
De : Andrei Izrantcev <notifications@github.com>
Envoyé : vendredi 9 février 2018 14:25
À : bdancer/blender-for-vray
Cc : julvvvv; Author
Objet : Re: [bdancer/blender-for-vray] Trouble with blender linux 16.04 Xenial Xerus (#235)


I can't open this screenshot, it shows nothing.

  1.  Have you installed Blender build from https://nightlies.chaosgroup.com/#/blender ?
Sign in | Chaos Group<https://nightlies.chaosgroup.com/#/blender>
nightlies.chaosgroup.com
Password Forgot your password? Don't have an account yet? Create Account

  2.  Have you installed V-Ray Standalone?
  3.  Could you upload your screenshot ones again?
  4.  Any errors in console?

**Comment by julvvvv** [comment]
well after an fresh install of xubuntu 12.04 lts. with blender 2.75.

No start..

[cid:7b726ec1-0ad5-4abf-8f0d-13f956ff86e6]

for the little story.

i'm an old user vrayc4d, i contributed for web community .

http://forum.vrayforc4d.com/index.php?threads/4255/


<http://forum.vrayforc4d.com/index.php?threads/4255/>

<http://forum.vrayforc4d.com/index.php?threads/4255/>http://forum.vrayforc4d.com/index.php?threads/5113/

welll is to old 1.8 vray in 2009..

[cid:63193b3c-5df3-4d89-b764-4d70944e6635]

[cid:c5808850-f425-433d-ad34-84d3332950d1]
[cid:b24c3450-f9a4-4830-8462-08c38277e6fe]

[cid:221e0ce2-ba18-4860-b5be-7111d8848f33]

[cid:93059124-3915-4908-bd01-0c5457996519]


[cid:6b6b85a2-55cc-4651-8801-04ff05885225]




________________________________
De : Andrei Izrantcev <notifications@github.com>
Envoyé : vendredi 9 février 2018 14:25
À : bdancer/blender-for-vray
Cc : julvvvv; Author
Objet : Re: [bdancer/blender-for-vray] Trouble with blender linux 16.04 Xenial Xerus (#235)


I can't open this screenshot, it shows nothing.

  1.  Have you installed Blender build from https://nightlies.chaosgroup.com/#/blender ?
Sign in | Chaos Group<https://nightlies.chaosgroup.com/#/blender>
nightlies.chaosgroup.com
Password Forgot your password? Don't have an account yet? Create Account

  2.  Have you installed V-Ray Standalone?
  3.  Could you upload your screenshot ones again?
  4.  Any errors in console?

**Comment by bdancer** [comment]
Exporter does not work with the regular Blender builds.
You need to install the one from here https://nightlies.chaosgroup.com/#/blender.
It already contains everything that's needed (except V-Ray Standalone that you've already installed).

**Comment by julvvvv** [comment]
humm so complicate for me. after read lot of experience on the chaosforum..
Lot of exemple with ubuntu of many version 12.04 .. 14.04 server..
After a news install
With the last blendervray in nightlies server, i see the sh terminal.. but not licence.
![screenshot at 2018-02-12 20 30 27](https://user-images.githubusercontent.com/19374263/36116034-35b6d2bc-1035-11e8-9b75-29e7c0c8a390.png)

**Comment by bdancer** [comment]
So here is your error in red. Is the license server running?

**Comment by julvvvv** [comment]
Yes,

And don't understant why..

A Start in the News install of Ubuntu 16.04
     Install blender
     Install vraystandalone
     Install blendervray
 And install servervray...
      Local test with hostlocal 30304... Enter my id, and pass but No run ..



Envoyé de mon iPad

Le 13 févr. 2018 à 12:43, Andrei Izrantcev <notifications@github.com<mailto:notifications@github.com>> a écrit :


So here is your error in red. Is the license server running?

**Comment by julvvvv** [comment]
With the server install it's run!!

![bb-run](https://user-images.githubusercontent.com/19374263/36154635-583854f8-10d2-11e8-947e-52b2864a3086.png)

**Comment by bdancer** [comment]
Great!
