### ISSUE TITLE
vb30: autosmooth not working 

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#80]
Blender 2.73 (vrayblender3-2.73-57844-1568a4b-3ccddec-x86_64-windows.exe)

Auto Smooth option is not working, all faces are getting smoothed, but we get a similar result to using an EdgeSplit Modifier.

![autosmooth](https://cloud.githubusercontent.com/assets/338739/5830455/cf188edc-a107-11e4-9176-f7975d524291.jpg)

**Comment by bdancer** [comment]
I'll need a scene for this, because it was supported for a long time already...

**Comment by cyberlecs** [comment]
Hi, just sent it to your email.

**Comment by cyberlecs** [comment]
With autosmooth angle=180 it's working fine.
Thanks bdancer!

**Comment by cyberlecs** [comment]
In the recent builds, using angle=180 is not working anymore.
If I enable autosmooth all faces are allways sharp.

blendfile: http://www.pasteall.org/blend/34563

![autosmooth](https://cloud.githubusercontent.com/assets/338739/6287832/bd0417c8-b8fb-11e4-9946-737c0a1466c6.jpg)

**Comment by bdancer** [comment]
Thanks, fixed with https://github.com/bdancer/blender-for-vray/commit/9a0dd9470734427f6106f6d33eb14c41fa44bf58
New builds in progress
