### ISSUE TITLE
vb30: Lens Effects settings are not transfered from blender to VFB

### ISSUE THREAD

**Issue by cyberlecs** [bdancer/blender-for-vray#81]
Blender 2.73 (vrayblender3-2.73-57844-1568a4b-3ccddec-x86_64-windows.exe)

Lens Effects settings inside Blender are not transfered to VFB, this can be an issue when doing batch (camera loop) rendering with autosave option - and you can't disable autosave (output option) because camera loop closes the last VFB to start a new one.

![lenseffects](https://cloud.githubusercontent.com/assets/338739/5830626/86ab5c26-a10a-11e4-9990-2d96c8e805bf.jpg)

**Comment by bdancer** [comment]
This could be a V-Ray issue, I'll check.
