### ISSUE TITLE
vb30: Exporter performce twice slower than vb25

### ISSUE THREAD

**Issue by dimitarkolev** [bdancer/blender-for-vray#84]
We noticed that the performance of the vb30 exporter is almost twice slower compared to vb25. We used one and the same test scene with single frame (This is common in ArchViz). Out tests showed 15s for vb25 and 35s for vb30.
From what i understood the only difference between both exporters is gzip compression of meshes. I believe that this might cause the performance issue. GZip mesh compression is great in some scenarios - when working with animations but when you are not rendering animations but setting up materials and doing a lot of region renders on complex scenes this performance is slowing you a lot.
It will be good to have this GZip mesh compression as an option or much better enabled only when exporting animations or doing distributed rendering.

**Comment by bdancer** [comment]
I've added an option "Export Format" under "Exporter" panel:
https://github.com/bdancer/blender-for-vray/commit/0a5fe8ccc63058f3003b988f500aeb27b423d2ba
https://github.com/bdancer/vb30/commit/349e429ee16088aa7c1e13ae3aa60f0b1a823184

Try the "HEX" format.

**Comment by dimitarkolev** [comment]
Just managed to test the new build and from what i see its great :) Using the HEX option speeds up the export from 36s to just 6s, which is amazing when you are playing with regions and doing a lot of test renders.
