### ISSUE TITLE
vb30: WireColor doesn't work

### ISSUE THREAD

**Issue by coolerinc** [bdancer/blender-for-vray#87]
WireColor in ColorChannel doesn't affect anything result, build 2015-02-09
I tried to change Object Color on Object tab and Viewport Color but it doesn't work
can you check it please?!

**Comment by bdancer** [comment]
Could you pls upload a test scene?

**Comment by coolerinc** [comment]
here it is http://www.pasteall.org/blend/34317

**Comment by bdancer** [comment]
This is 3dsmax only channel. It'll be removed. Use "Render ID", "Node ID", "MultiMatte", etc.
