### ISSUE TITLE
vb30: Displacement - view dependent FAIL

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#90]
Hello,

I sent you scene (we transfer). Please check, because in my opinion view dependent option in displacement not working. There is sample scene with 2 camera. The final image from camera 1 and 2 are different.

My blender: b825b71

**Comment by kontrolermpl** [comment]
http://we.tl/wU6g5xzvLP

**Comment by bdancer** [comment]
Why then "View dependent" is turned off?

![2015_03_31_001](https://cloud.githubusercontent.com/assets/319784/6917225/70c9b31c-d7ab-11e4-93a6-381548668776.png)

If "Use Globals" is off then you should use this panel.

**Comment by kontrolermpl** [comment]
This is turned off, because I want to get the same result regardless of the camera distance. Is this right?

**Comment by kontrolermpl** [comment]
Ok, all is ok. I was made to small noise texture element.
