### ISSUE TITLE
"Render Channels" Compositing re-import (EXR)

### ISSUE THREAD

**Issue by fmees** [bdancer/blender-for-vray#91]
Hi,
Is it possible to work with the "Image to Blender" Option with the declared Channels in the "V-Ray Scene Node Editor".

For Example: I want to export only the Diffuse Channel. When I hit render the Channel is showing up in the Exporter but not in the Compositor.

![render-channels](https://cloud.githubusercontent.com/assets/10790142/7017042/5a9a6ac8-dcf1-11e4-9a1c-ed358aca5349.png)

**Comment by bdancer** [comment]
Compositor is not directly supported. Use input "Image" node.
