### ISSUE TITLE
vb30: SSS 2, Single Scatter

### ISSUE THREAD

**Issue by jkntdo** [bdancer/blender-for-vray#92]
Hello, I'm using the latest nightly build. Is there a way to change Single Scatter mode for SSS 2 material?  For example : raytraced (refractive),  raytraced (solid) ,etc

**Comment by bdancer** [comment]
Thanks! Fixed with: https://github.com/bdancer/plugins_desc/commit/a58d6f12481400209e49417dd809abf02a808f0b Update exporter (check notes here https://github.com/bdancer/vb30/wiki) or wait for new builds.
