### ISSUE TITLE
vb30: Camera - orthographic setting

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#97]
I tried to set up orthographic camera in my scene, but it seems that camera option don't work properly. in other words - this option (cylindrical, fisheye etc.) doesn't work.

My Blender is 2.74.4 b825b71 from 2015-03-30

**Comment by bdancer** [comment]
Do you have physical camera enabled? Try without.

**Comment by kontrolermpl** [comment]
Yes I have. So I turn this off, but now I have over exposed image, you know why. So in my opinion, there's no chance to have physical camera and keep orthographic option. Will be it implement in the future?

**Comment by kontrolermpl** [comment]
Hello, anybody?

**Comment by bdancer** [comment]
I haven't heard of such plans.

**Comment by kontrolermpl** [comment]
Can you check it?

**Comment by bdancer** [comment]
There are no such plans at the moment.
