### ISSUE TITLE
vb30: Blending materials and region renderer

### ISSUE THREAD

**Issue by pietruh00s** [bdancer/blender-for-vray#98]
Hi, where I can find node for blending two materials with image mask. I've found only node to blend two color textures. Or it is my fault, caused by incorrect node setup. 

Secondly is there any way to get region renderer work with blender? It will be very helpful to have this feature.

Thanks

**Comment by bdancer** [comment]
1. Use BRDF -> Layered, connect mask into the Weight socket.
2. It already works, completely the same as in Blender, just select the region with Shift+B.

**Comment by pietruh00s** [comment]
1) I forgot about that node! I used it before and it slipped my mind :D 
2) I know that but, it starts to render in new window, without last render in backround and new in region, as it is in 3dsmax

**Comment by bdancer** [comment]
2. This is currently impossible.
