### ISSUE TITLE
vb25 exporter on Blender 2.74

### ISSUE THREAD

**Issue by jkntdo** [bdancer/blender-for-vray#99]
Hello, sorry if this has been asked before or I'm missing something. Is there anywhere Blender version 2.74 with vb25 available for download? Or can I download the vb25 exporter and install it myself?

**Comment by bdancer** [comment]
Hi!
vb25 exporter is no longer supported and doesn't work with any new Blender versions.

**Comment by jkntdo** [comment]
Thanks for fast response :)
